### ISSUE TITLE
Directioness metric in plotting pie charts

### ISSUE THREAD

**Issue by mx60s** [don-tpanic/Space#1]
Hi!

It might be my own misunderstanding, but why is unit_chart_info[unit_index, 6] (which is np.mean(heatmap)) being used to classify direction cells, while unit_chart_info[unit_index, 10] (length of resultant hd vector) is used for the lesion studies? Using the former replicates the pie charts shown in the paper, but I don't understand the logic, and plotting these direction cells just shows cells with very large activations.

Which should be used when plotting direction cells?

https://github.com/don-tpanic/Space/blob/41bf362c41cc08f4c341f34d92018da614c89711/figures_paper.py#L1710

Sorry if I'm missing something, and thank you!

**Comment by don-tpanic** [comment]
Thank you for spotting my mistake! So sorry for this, I will update the code and figures asap.

**Comment by don-tpanic** [comment]
@mx60s OK, I fixed this mistake. https://github.com/don-tpanic/Space/blob/units/unit_metric_computers.py#L272

Actually there was another issue regarding plotting the distribution of unit types, which was that active units with no specified types were ignored. It was fixed in my PR (https://github.com/don-tpanic/Space/blob/units/unit_metric_computers.py#L284) 

Finally, that PR did a little refactoring to move the unit classification code out of `figures_paper.py`. You can find the latest code (after you pull) here: https://github.com/don-tpanic/Space/blob/units/unit_metric_computers.py#L284

**Comment by mx60s** [comment]
Awesome, thanks so much for the speedy fix!
